name: Sync Discovered API with APIConnect

on: [pull_request, workflow_dispatch, push]

env:
  API_HOST: env5717743.a-vir-c1.apiconnect.ipaas.automation.ibm.com
  PLATFORM_API_PREFIX: platform-api
  PROVIDER_ORG: env5717743
  API_FILES: api-demo.yaml 

jobs:
  run-discovery:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set Node to Ignore SSL Globally
      run: echo "NODE_TLS_REJECT_UNAUTHORIZED=0" >> $GITHUB_ENV

    - name: Difference
      id: difference-output
      run: |
        # Menggunakan fallback jika git diff gagal pada push pertama
        echo "action_updates=$(git diff --name-only HEAD^ HEAD 2>/dev/null || echo '${{ env.API_FILES }}')" >> $GITHUB_OUTPUT

    - uses: ibm-apiconnect/apic-discovery-action@main
      id: discover-apis
      with:
        api_host: ${{ env.API_HOST }}
        platform_api_prefix: ${{ env.PLATFORM_API_PREFIX }}
        provider_org: ${{ env.PROVIDER_ORG }}
        api_key: ${{ secrets.apicApikey }}
        api_files: ${{ env.API_FILES }}
        resync_check: true
        git_diff: ${{ steps.difference-output.outputs.action_updates }}
        insecure_skip_tls_verify: true #

    - name: Display the action-result
      run: |
        echo "Result: ${{ steps.discover-apis.outputs.action-result }}"
