name: Sync Discovered API with APIConnect

on: [pull_request, workflow_dispatch, push]

env:

  API_HOST: us-east-a.apiconnect.automation.ibm.com
  PLATFORM_API_PREFIX: platform-api
  PROVIDER_ORG: env9375973
  API_FILES: hello_1.0.0.yaml
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-discovery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate Git Diff
        id: difference-output
        run: |
          PREV_SHA=${{ github.event.before }}
          if [ "$PREV_SHA" == "0000000000000000000000000000000000000000" ] || [ -z "$PREV_SHA" ]; then
            PREV_SHA="HEAD~1"
          fi
          echo "action_updates=$(git diff --name-only --diff-filter=ACMRT $PREV_SHA ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT

      - name: Run APIC Discovery
        uses: ibm-apiconnect/apic-discovery-action@main
        id: discover-apis
        with:
          api_host: ${{ env.API_HOST }}
          platform_api_prefix: ${{ env.PLATFORM_API_PREFIX }}
          provider_org: ${{ env.PROVIDER_ORG }}
          api_key: ${{ secrets.Kunci_API }}
          api_files: ${{ env.API_FILES }}
          resync_check: true
          git_diff: ${{ steps.difference-output.outputs.action_updates }}
          insecure_skip_tls_verify: true
